Update dependencies
exonum/exonum-configuration pull request #81
Opened 2018-01-24 10:30 UTC by alekseysidorov

Just update logger version.

- Not a breaking change
- No need in updating docs
- No need in testing

2018-01-24 13:29 UTC, vitvakatu approved these changes

2018-01-24 13:30 UTC, vitvakatu requested changes

2018-01-24 13:30 UTC, vitvakatu commented on Cargo.toml
> +log = "0.4.0"
Wait, why it's not 0.41?

2018-01-24 13:34 UTC, alekseysidorov commented on Cargo.toml
> +log = "0.4.0"
So it happened.

2018-01-30 14:19 UTC, vitvakatu approved these changes

2018-01-30 14:19 UTC, vitvakatu commented on Cargo.toml
> +exonum = "0.5.0"
Do you want to make an actual update later?

2018-01-30 15:46 UTC, DarkEld3r commented
Closed in favor of #82.

2018-01-30 15:46 UTC, closed without merging